name: Movie Review Pipline

on:
  push:
    branches:
      - "*"
  
  pull_request:
    branches:
      - "*"

jobs:
  check_syntaxes:
    runs_on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.12"
      
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check lint code flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=100


build:
  name: Build & push image Docker
  runs-on: ubuntu-latest
  needs: check_syntaxes
  steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      env: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u $username -p $password

    - name: Build Docker image
      run: docker build . -t devibrahima/movie:latest

    - name: Push Docker Image To registry
      run: docker push devibrahima/movie:latest